### ISSUE TITLE
FEEDBACK obre uso de GITHUB y GIT

### ISSUE THREAD

**Issue by KatuGT** [joalvarez05/GigaStore#20]
![image](https://github.com/user-attachments/assets/2f97bdd1-1e90-4bc7-ba85-d92ffd858f55)

Les paso a dejar un consejo aqui, luego de que lo lean pueden cerrar esta "ISSUE"

@ramirofrias24  mas que nada para vos,  viendo las contribuciones figura que solo hiciste **1 (un) commit**, cualquiera ve eso así rápido y piensa que no participaste prácticamente, es por eso que es importante que vayas mandando commits por cada modulo que consideres "importante"  y no 1 solo commit gigante como hiciste vos, que veo que agregaste contenido para la pagina del "Carrito", "nosotros" y en el "navbar"

Luego de que lean este mensaje pueden cerrar esta Issue

**Comment by ramirofrias24** [comment]
Hola! Si no lo tuve presente, tuve que ir haciendo commits en vez de pasar entre proyectos lo codeado y hacer un sólo commit! Lo tendré presente para siempre ya que fué mi primera experiencia en un proyecto y se me escapó ese importante detalle🙌🏽
